openapi: 3.0.0
info:
  title: Account API Definitions
  version: 1.0.0
paths:
  /actiontypes:
    get:
      summary: Get a list of Actiontypes
      operationId: getActiontypes
      responses:
        200:
          description: OK
          content: {}
    post:
      summary: Create a new Actiontype
      operationId: createActiontype
      requestBody:
        description: An array of new Actiontype records
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActiontypeRequest'
        required: true
      responses:
        201:
          description: Created
          content: {}
      x-codegen-request-body-name: actiontypeRequest
  /actiontypes/{id}:
    get:
      summary: Get a specific Actiontype
      operationId: getActionType
      parameters:
        - name: id
          in: path
          description: ID of the Actiontype to fetch
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
          content: {}
  /actiontypes/search/{query}:
    get:
      summary: Search for an ActionType by Name
      operationId: findActionTypeByName
      parameters:
        - name: query
          in: path
          description: Search for an ActionType by Name
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content: {}
components:
  schemas:
    Actiontype:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
        descr:
          type: string
          nullable: true
    ActiontypeRequest:
      type: object
      properties:
        Data:
          type: array
          items:
            $ref: '#/components/schemas/Actiontype'
      description: An array of Actiontype objects
    ActiontypeResponse:
      type: object
      properties:
        Data:
          type: array
          items:
            $ref: '#/components/schemas/Actiontype'
      description: An array of Actiontype objects
